# Generated by Django 4.2.16 on 2024-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile2', '0002_tasteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='taste_profile_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='taste_profile_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TasteProfile',
        ),
    ]
