# Generated by Django 4.2.16 on 2024-09-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('track_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_id', models.IntegerField()),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_image', models.URLField(blank=True, max_length=500, null=True)),
                ('artist_id', models.IntegerField()),
                ('audio_url', models.URLField(max_length=500)),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('share_url', models.URLField(blank=True, max_length=500, null=True)),
                ('license_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfcc_mean', models.JSONField()),
                ('tempo', models.FloatField()),
                ('chroma_mean', models.JSONField(blank=True, null=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
    ]
