# Generated by Django 4.2.16 on 2024-09-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.IntegerField(default=0, unique=True)),
                ('track_number', models.CharField(default='0', max_length=10)),
                ('title', models.CharField(default='Unknown Title', max_length=255)),
                ('artist', models.CharField(default='Unknown Artist', max_length=255)),
                ('album', models.CharField(blank=True, default='Unknown Album', max_length=255, null=True)),
                ('url', models.URLField(default='http://example.com')),
                ('segment_start', models.IntegerField(default=0)),
                ('segment_end', models.IntegerField(default=0)),
                ('original_url', models.URLField(default='http://example.com')),
                ('mp3_path', models.CharField(default='Unknown Path', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Tag', max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255, unique=True)),
                ('track_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField()),
                ('track_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VisualContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='visual_content/')),
                ('mood', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visualcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfcc_mean', models.JSONField()),
                ('tempo', models.FloatField()),
                ('chroma_mean', models.JSONField(blank=True, null=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
    ]
