# Generated by Django 4.2.16 on 2024-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_url',
            new_name='audio_url',
        ),
        migrations.AddField(
            model_name='track',
            name='mp3_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
