# Generated by Django 4.2.16 on 2024-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_track_url_track_audio_url_track_mp3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='mp3_path',
            field=models.FileField(upload_to='downloads/'),
        ),
    ]
