# Generated by Django 4.2.16 on 2024-09-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_track_mp3_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='pro_license',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='share_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
