# Generated by Django 4.2.16 on 2024-09-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_song_uploaded_at_visualcontent_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='Unknown Artist', on_delete=django.db.models.deletion.CASCADE, to='home.artist'),
        ),
    ]
