# Generated by Django 4.2.16 on 2024-09-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_song_mp3_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.RemoveField(
            model_name='contentview',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='songview',
            name='song',
        ),
        migrations.RemoveField(
            model_name='songview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visualcontent',
            name='song',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ContentView',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='SongView',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='VisualContent',
        ),
    ]
