# Generated by Django 4.2.16 on 2024-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_alter_message_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='group_picture',
            field=models.ImageField(default='default.jpg', upload_to='group_pics/'),
        ),
    ]
